### ISSUE TITLE
Command invalid

### ISSUE THREAD

**Issue by raphaelcheung** [0xC0000054/sc4-growify#1]
I followed the instructions to execute command `growify residential low true` in the game, but the prompt said it affected 0 buildings. In reality, there are at least hundreds of buildings that should be labeled

**Comment by 0xC0000054** [comment]
Are the buildings from a mod?

The DLL detects the building type using the building exemplar Purpose property (0x27812833), for a residential building this value must be set to Residence.

**Comment by raphaelcheung** [comment]
> Are the buildings from a mod?
> 
> The DLL detects the building type using the building exemplar Purpose property (0x27812833), for a residential building this value must be set to Residence.

All residential buildings, mod and Native.

and, I tried debugging your code, found that it couldn't compile
![image](https://github.com/0xC0000054/sc4-growify/assets/50747339/d7615c5b-2e58-4d34-8705-6f1a1ce2ac8c)

**Comment by raphaelcheung** [comment]
> Are the buildings from a mod?
> 
> The DLL detects the building type using the building exemplar Purpose property (0x27812833), for a residential building this value must be set to Residence.

I tried Residence, but it didn't work either

and, I tried debugging your code, found that it couldn't compile
![image](https://github.com/0xC0000054/sc4-growify/assets/50747339/9a3b5033-8c14-4308-8030-7e54d42dcd0d)

**Comment by 0xC0000054** [comment]
> I tried Residence, but it didn't work either

I have no idea what the issue could be.

> and, I tried debugging your code, found that it couldn't compile

Those dependencies are installed through the vcpkg [integration](https://github.com/microsoft/vcpkg?tab=readme-ov-file#quick-start-windows) with Visual Studio 2022. I missed that in the prerequisites.

**Comment by raphaelcheung** [comment]
> > I tried Residence, but it didn't work either
> 
> I have no idea what the issue could be.
> 
> > and, I tried debugging your code, found that it couldn't compile
> 
> Those dependencies are installed through the vcpkg [integration](https://github.com/microsoft/vcpkg?tab=readme-ov-file#quick-start-windows) with Visual Studio 2022. I missed that in the prerequisites.

I fixed the boost related issues after installing vcpkg
But there is still one error:  `“x86/arch_x86.h”: No such file or directory`

Is there something else I'm missing?

**Comment by 0xC0000054** [comment]
Looks like that header is part of EASTL, and it was mistakenly excluded by a rule in the gitignore file.

Edit: fixed in a recent commit.

**Comment by raphaelcheung** [comment]
> Looks like that header is part of EASTL, and it was mistakenly excluded by a rule in the gitignore file.
> 
> Edit: fixed in a recent commit.

Thanks to your efforts, I have been able to compile and have written a similar plugin after learning about your project, allowing you to specify the building type and minimum capacity to set the history.

https://github.com/raphaelcheung/SC4Historical

**Comment by 0xC0000054** [comment]
Nice. 

Did you ever figure out why the Growify command was affecting 0 buildings?

**Comment by raphaelcheung** [comment]
> Nice.
> 
> Did you ever figure out why the Growify command was affecting 0 buildings?

Because my demand is related to the building capacity, I didn't track and debug your project. 

I suspect that there may be a problem with my understanding of the correct effect of your plug-in. After all, my English is poor.

**Comment by 0xC0000054** [comment]
This plugin would only work for buildings that were placed with the `BuildingPlop` cheat,

**Comment by raphaelcheung** [comment]
> BuildingPlop

It only works for the growing buildings next to `BuildingPlop`?

**Comment by raphaelcheung** [comment]
> This plugin would only work for buildings that were placed with the `BuildingPlop` cheat,

It only works for the growing buildings next to BuildingPlop?

**Comment by 0xC0000054** [comment]
It changes the building type for buildings that were placed with the `BuildingPlop` cheat from plopped to growable.

**Comment by raphaelcheung** [comment]
> It changes the building type for buildings that were placed with the `BuildingPlop` cheat from plopped to growable.

For example, if I put two `BuildingPlop` in a planned business area, this `BuildingPlop` will become growable after using your plug-in?

**Comment by 0xC0000054** [comment]
> For example, if I put two `BuildingPlop` in a planned business area, this `BuildingPlop` will become growable after using your plug-in?

Yes.
You can check it using the advanced building hover query tool tip, to activate that mode hold `Control + Alt + Shift` and hover over the building.
Here is an example of that from the GitHub Readme:

Before using the plugin, the `Zoned` line says `Plopped Bldg`:
![Before](https://github.com/0xC0000054/sc4-growify/raw/main/images/Before.jpg))

After using the plugin, the `Zoned` line says `C##`:
![After](https://github.com/0xC0000054/sc4-growify/raw/main/images/After.jpg))

**Comment by raphaelcheung** [comment]
> > For example, if I put two `BuildingPlop` in a planned business area, this `BuildingPlop` will become growable after using your plug-in?
> 
> Yes. You can check it using the advanced building hover query tool tip, to activate that mode hold `Control + Alt + Shift` and hover over the building. Here is an example of that from the GitHub Readme:
> 
> Before using the plugin, the `Zoned` line says `Plopped Bldg`: ![Before](https://github.com/0xC0000054/sc4-growify/raw/main/images/Before.jpg))
> 
> After using the plugin, the `Zoned` line says `C##`: ![After](https://github.com/0xC0000054/sc4-growify/raw/main/images/After.jpg))

I placed two plop buildings with jobs, and after using the plug-in command, I was prompted that two of them took effect, but I didn't see the actual difference from other places.

**Comment by 0xC0000054** [comment]
I just fixed a bug that may be related. Some 3rd-party buildings store the Purpose property as an one item array, which the plugin could not handle. Fixed in version 1.0.1.
